=== gonetto/GonettoFCApiClientBundle/JSONSchema/DataResponseSchema.json
{
    "$schema": "http://json-schema.org/schema#",
    "title": "Match customers",
    "description": "This is a schema that matches customers.",
    "type": "object",
    "properties": {
        "kunden": {
            "$ref": "CustomersSchema.json"
        },
        "kundenDeleted": {
            "$ref": "DeletedSchema.json"
        },
        "vertraege": {
            "$ref": "ContractsSchema.json"
        },
        "vertraegeDeleted": {
            "$ref": "DeletedSchema.json"
        },
        "dokumente": {
            "$ref": "DocumentsSchema.json"
        },
        "dokumenteDeleted": {
            "$ref": "DeletedSchema.json"
        }
    }
}

=== gonetto/GonettoFCApiClientBundle/Tests/Service/CustomerClientNew/FinanceConsultApiResponse.json
{
    "kunden": [
        {
            "oid": "19P1CF",
            "email": "swen.tyrasa@gmail.com",
            "vorname": "Swen",
            "nachname": "Tyrasa",
            "firma": "",
            "strasse": "Dorfstr.  21",
            "plz": "07646",
            "ort": "Eineborn",
            "iban": ""
        }
    ],
    "kundenDeleted": [
        "1B6PS1"
    ],
    "vertraege": [
        {
            "oid": "SB1CK",
            "kundeID": "S89YN",
            "beitrag": 656.9,
            "gesellschaft": "DEVK Versicherungen",
            "gonetto-id": "",
            "hauptfälligkeit": "2006-04-01T00:00:00",
            "produkt": "Wohngebäude",
            "vermittlungsdatum": "2018-03-27T00:00:00",
            "vertragsende": "2019-04-01T00:00:00",
            "vertragsnummer": "00011663394",
            "zahlungsweise": "jahrlich"
        }
    ],
    "vertraegeDeleted": [
        "AB45U"
    ],
    "dokumente": [
        {
            "oid": "1B5O3V",
            "vertragID": "19DB5Y",
            "beschreibung": "Röthel, Thomas",
            "datum": "2019-02-04T13:26:58"
        }
    ],
    "dokumenteDeleted": [
        "19CTC5"
    ]
}

=== gonetto/GonettoFCApiClientBundle/Tests/Service/CustomerClient/ApiDataResponse.json
{
    "kunden": [
        {
            "oid": "19P1CF",
            "email": "anna.musterfrau@domain.tld",
            "vorname": "Anna",
            "nachname": "Musterfrau",
            "firma": "Beispielfirma",
            "strasse": "Beispielstr. 2",
            "plz": "54321",
            "ort": "Beispielstadt",
            "iban": "DE02500105170137075030"
        }
    ],
    "kundenDeleted": [
        "1B6PS1"
    ],
    "vertraege": [
        {
            "oid": "SB1CK",
            "kundeID": "19P1CF",
            "beitrag": 656.9,
            "gesellschaft": "DEVK Versicherungen",
            "hauptfälligkeit": "2006-04-01T00:00:00",
            "produkt": "Wohngebäude",
            "vermittlungsdatum": "2018-03-27T11:21:37",
            "vertragsende": "2019-04-01T00:00:00",
            "vertragsnummer": "2397868001",
            "zahlungsweise": "jahrlich"
        }
    ],
    "vertraegeDeleted": [
        "AB45U"
    ],
    "dokumente": [
        {
            "oid": "1B5O3V",
            "vertragID": "19DB5Y",
            "beschreibung": "Röthel, Thomas",
            "art": 2,
            "datum": "2019-02-04T13:26:58"
        }
    ],
    "dokumenteDeleted": [
        "19CTC5"
    ]
}
